services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - ${POSTGRESDB_PORT}:${POSTGRESDB_PORT}
    volumes:
      - db:/var/lib/postgres
  # app:
  #   depends_on:
  #     - postgresdb
  #   build: ./Dockerfile
  #   restart: unless-stopped
  #   env_file: ./env/development.env
  #   ports:
  #     - $PORT:$PORT
  #   environment:
  #     DB_HOST: postgresdb
  #     DB_USER: $POSTGRESDB_USER
  #     DB_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
  #     DB_NAME: $POSTGRESDB_DATABASE
  #     DB_PORT: $PORT
  #   stdin_open: true
  #   tty: true

volumes:
  db:
